"""table users

Revision ID: 3dee12bad14e
Revises: 
Create Date: 2026-08-04 18:30:00.798969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dee12bad14e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.add_column('caixinhas', sa.Column('nome', sa.String(), nullable=False))
    op.add_column('caixinhas', sa.Column('valor', sa.Float(), nullable=False))
    op.add_column('caixinhas', sa.Column('id_banco', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'caixinhas', 'bancos', ['id_banco'], ['id'])
    op.add_column('gastos', sa.Column('nome', sa.String(), nullable=False))
    op.add_column('gastos', sa.Column('valor', sa.Float(), nullable=False))
    op.add_column('gastos', sa.Column('tipo', sa.String(), nullable=False))
    op.add_column('gastos', sa.Column('id_banco', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gastos', 'bancos', ['id_banco'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gastos', type_='foreignkey')
    op.drop_column('gastos', 'id_banco')
    op.drop_column('gastos', 'tipo')
    op.drop_column('gastos', 'valor')
    op.drop_column('gastos', 'nome')
    op.drop_constraint(None, 'caixinhas', type_='foreignkey')
    op.drop_column('caixinhas', 'id_banco')
    op.drop_column('caixinhas', 'valor')
    op.drop_column('caixinhas', 'nome')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
